### ISSUE TITLE
ToDo List for public release

### ISSUE THREAD

**Issue by eneskemalergin** [eneskemalergin/eneskemalergin.github.io#1]
- [x] Select a One-Page Responsive Template to use a main page/portfolio
- [x] Tweak the structure of the website if necessary
- [x] Select pictures to use in the website
- [x] Arrange a better color-scheme for the website
- [x] Finalize the design choice 
- [x] Add content to appropriate sections
- [x] Check all the links
- [x] Make the repo public 
- [x] Rename the repo as eneskemalergin.github.io
- [x] Fix the Favicon for the main page
- [x] Adding whitish background for pictures,
- [x] Check the links on Blog and fix all the issues
- [ ] Connect Blog and Photo Journal to the Main Website
- [ ] Check for domains, that I could use (eneskemalergin.me could be nice)
